name: fast_cached_network_image
description: A flutter package to cache network image fastly without any native dependencies.You can add beautiful loaders, percentage indicators and error builder.
version: 1.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  firebase_storage: ^11.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
